version: "3.8"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.1.3:5000/caddy-custom:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 9180:9180
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    env_file: ./.env
